on:
  push:
    tags: ["argocd-extensions-v*"]
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tar czf extensions.tar.gz -C argocd --transform 's,^extensions,resources,' extensions
      - run: gh release create "$GITHUB_REF_NAME" extensions.tar.gz --title "$GITHUB_REF_NAME"
        env:
          GH_TOKEN: ${{ github.token }}
